#!/bin/bash
clear
pkill -f ws-epro
echo " INSTALANDO O SCRIPT WEBSOCKS PRO"
sleep 1
cd

#Install ws-epro
wget -q --show-progress --load-cookies /tmp/cookies.txt "https://github.com/BaseDeTudoKobras/Scripts/raw/WS-PRO/ws-epro" -O /usr/local/bin/ws-epro && rm -rf /tmp/cookies.txt
chmod +x /usr/local/bin/ws-epro

#ws-epro service
wget -q --show-progress --load-cookies /tmp/cookies.txt "https://github.com/BaseDeTudoKobras/Scripts/raw/WS-PRO/ws-epro.service" -O /etc/systemd/system/ws-epro.service && rm -rf /tmp/cookies.txt
chmod +x /etc/systemd/system/ws-epro.service

#ws-epro port
wget -q --show-progress --load-cookies /tmp/cookies.txt "https://github.com/BaseDeTudoKobras/Scripts/raw/WS-PRO/ws-port" -O /usr/bin/ws-port && rm -rf /tmp/cookies.txt
chmod +x /usr/bin/ws-port

#seting port
clear
echo " INFORME AS PORTAS"
sleep 1
read -p " PORTA DE ESCUTA : " openssh
read -p " PORTA DE CONEXAO : " wsopenssh
WS_DIR=/usr/local/etc/ws-epro
if [ -d "$WS_DIR" ]; then # if it exists,delete it.
    rm -rf "$WS_DIR"
fi
mkdir "$WS_DIR"
echo " CONFIGURANDO SERVIDOR ESPERE..."
sleep 0.5
echo "# verbose level 0=info, 1=verbose, 2=very verbose" >> /usr/local/etc/ws-epro/config.yml
echo "verbose: 0" >> /usr/local/etc/ws-epro/config.yml
echo "listen:"  >> /usr/local/etc/ws-epro/config.yml

#seting port
echo "##openssh" >> /usr/local/etc/ws-epro/config.yml
echo "- target_host: 127.0.0.1" >> /usr/local/etc/ws-epro/config.yml
echo "##portopenssh" >> /usr/local/etc/ws-epro/config.yml
echo "  target_port: $openssh" >> /usr/local/etc/ws-epro/config.yml
echo "##wsopenssh" >> /usr/local/etc/ws-epro/config.yml
echo "  listen_port: $wsopenssh" >> /usr/local/etc/ws-epro/config.yml

chmod +x /usr/local/etc/ws-epro/config.yml

#Enable & Start service
systemctl enable ws-epro
systemctl start ws-epro

echo " SERVIDOR CONFIGURADO PARA WEBSOCKET PRO..."
sleep 0.3
clear
LP='\033[1;32m'
NC='\033[0m' # No Color
echo -e "${LP}"
echo    "
    KOBRAS VPN
   WEBSOCKS PRO
"

echo    " SCRIPT WEBSOCKET CLOUDFLARE PRO "
echo    ""
echo    " KOBRAS VPN"
echo    ""
echo    " Miguel Melo"
echo    ""
echo    " ╔════════════════════╗"
echo    "   Porta de ESCUTA: $openssh"
echo    "   Porta de CONEXAO: $wsopenssh"
echo    " ╚════════════════════╝"
echo    ""
echo    " WEBSOCKET SEM PLANO PRO DA CLOUDFLARE"
echo    "---------------------------------------"
echo    ""
echo    " PARA TROCAR A PORTA DE CONEXAO USE O COMANDO: ws-port"
echo    "---------------------------------------"
echo    ""
echo    " PAYLOAD PADRAO"
echo    ""
echo    " GET / HTTP/1.1[crlf]Host: Dominio[crlf]Upgrade: websocket[crlf][crlf]"
echo    "---------------------------------------"
echo -e "${NC}"
rm -rf install-ws && cat /dev/null > ~/.bash_history && history -c
